export const SCHEDULE_URL = '/schedule'
export const NEWS_URL = '/news'
export const ABOUT_URL = '/about'
export const MUSIC_URL = '/music'
export const PHOTOS_URL = '/photos'
export const VIDEOS_URL = '/videos'
export const CONTACTS_URL = '/contacts'
